version: '2'

services:
  php:
    build:
      context: .
    links:
      - mysql:mysql
    ports:
      - "80:80"
    volumes:
      - ./../../xenforo:/var/www/html
      - ./..:/var/www/html/src/addons
      - ./../../xenforo/src/addons/XF:/var/www/html/src/addons/XF
      - ./.data/external:/var/www/html/data
      - ./.data/internal:/var/www/html/internal_data

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'xenforo2'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
